"""Initial migration

Revision ID: aef5cf5580db
Revises: 
Create Date: 2025-01-15 09:34:36.068146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aef5cf5580db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='schedule_db') as batch_op:
        batch_op.drop_index('openid')

    op.drop_table('users', schema='schedule_db')
    op.drop_table('categories', schema='schedule_db')
    with op.batch_alter_table('statistics', schema='schedule_db') as batch_op:
        batch_op.drop_index('idx_user_date')

    op.drop_table('statistics', schema='schedule_db')
    op.drop_table('tasks', schema='schedule_db')
    op.drop_table('schedules', schema='schedule_db')
    with op.batch_alter_table('course_master', schema=None) as batch_op:
        batch_op.alter_column('course_code',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='课程编码',
               existing_nullable=False)
        batch_op.alter_column('course_name',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='课程名称',
               existing_nullable=False)
        batch_op.alter_column('course_type',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='课程类型',
               existing_nullable=False)
        batch_op.alter_column('course_keywords',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='课程关键词',
               existing_nullable=True)
        batch_op.alter_column('course_enabled',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('creator_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='创建者ID',
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_course_master_course_id'), ['course_id'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='课程主表'
    )

    with op.batch_alter_table('course_user', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
        batch_op.alter_column('course_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='课程ID',
               existing_nullable=False)
        batch_op.alter_column('course_alias',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='课程别名',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='教师姓名',
               existing_nullable=True)
        batch_op.alter_column('classroom',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='教室',
               existing_nullable=True)
        batch_op.alter_column('course_color',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='显示颜色',
               existing_nullable=True,
               existing_server_default=sa.text("'#1890FF'"))
        batch_op.alter_column('course_remark',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_course_user_course_user_id'), ['course_user_id'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='用户课程表'
    )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('openid',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='微信openid',
               existing_nullable=False)
        batch_op.alter_column('nickname',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='用户昵称',
               existing_nullable=True)
        batch_op.alter_column('avatar_url',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='头像URL',
               existing_nullable=True)
        batch_op.alter_column('theme_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='主题ID',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('province',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='省份',
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='城市',
               existing_nullable=True)
        batch_op.alter_column('school',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='学校名称',
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=16),
               comment=None,
               existing_comment='用户角色：user/admin',
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='用户表'
    )

    with op.batch_alter_table('user_schedule', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
        batch_op.alter_column('day_of_week',
               existing_type=mysql.TINYINT(display_width=4),
               comment=None,
               existing_comment='星期几(1-7)',
               existing_nullable=False)
        batch_op.alter_column('course_user_id1',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='第1节课',
               existing_nullable=True)
        batch_op.alter_column('course_user_id2',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='第2节课',
               existing_nullable=True)
        batch_op.alter_column('course_user_id3',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='第3节课',
               existing_nullable=True)
        batch_op.alter_column('course_user_id4',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='第4节课',
               existing_nullable=True)
        batch_op.alter_column('course_user_id5',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='第5节课',
               existing_nullable=True)
        batch_op.alter_column('course_user_id6',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='第6节课',
               existing_nullable=True)
        batch_op.alter_column('course_user_id7',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='第7节课',
               existing_nullable=True)
        batch_op.alter_column('course_user_id8',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='第8节课',
               existing_nullable=True)
        batch_op.alter_column('course_user_id9',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='第9节课',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_user_schedule_schedule_id'), ['schedule_id'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='用户课表'
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_schedule', schema=None) as batch_op:
        batch_op.create_table_comment(
        '用户课表',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_user_schedule_schedule_id'))
        batch_op.alter_column('course_user_id9',
               existing_type=mysql.BIGINT(display_width=20),
               comment='第9节课',
               existing_nullable=True)
        batch_op.alter_column('course_user_id8',
               existing_type=mysql.BIGINT(display_width=20),
               comment='第8节课',
               existing_nullable=True)
        batch_op.alter_column('course_user_id7',
               existing_type=mysql.BIGINT(display_width=20),
               comment='第7节课',
               existing_nullable=True)
        batch_op.alter_column('course_user_id6',
               existing_type=mysql.BIGINT(display_width=20),
               comment='第6节课',
               existing_nullable=True)
        batch_op.alter_column('course_user_id5',
               existing_type=mysql.BIGINT(display_width=20),
               comment='第5节课',
               existing_nullable=True)
        batch_op.alter_column('course_user_id4',
               existing_type=mysql.BIGINT(display_width=20),
               comment='第4节课',
               existing_nullable=True)
        batch_op.alter_column('course_user_id3',
               existing_type=mysql.BIGINT(display_width=20),
               comment='第3节课',
               existing_nullable=True)
        batch_op.alter_column('course_user_id2',
               existing_type=mysql.BIGINT(display_width=20),
               comment='第2节课',
               existing_nullable=True)
        batch_op.alter_column('course_user_id1',
               existing_type=mysql.BIGINT(display_width=20),
               comment='第1节课',
               existing_nullable=True)
        batch_op.alter_column('day_of_week',
               existing_type=mysql.TINYINT(display_width=4),
               comment='星期几(1-7)',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='用户ID',
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_table_comment(
        '用户表',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_user_id'))
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=16),
               comment='用户角色：user/admin',
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))
        batch_op.alter_column('school',
               existing_type=mysql.VARCHAR(length=100),
               comment='学校名称',
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(length=50),
               comment='城市',
               existing_nullable=True)
        batch_op.alter_column('province',
               existing_type=mysql.VARCHAR(length=50),
               comment='省份',
               existing_nullable=True)
        batch_op.alter_column('theme_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='主题ID',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('avatar_url',
               existing_type=mysql.VARCHAR(length=255),
               comment='头像URL',
               existing_nullable=True)
        batch_op.alter_column('nickname',
               existing_type=mysql.VARCHAR(length=64),
               comment='用户昵称',
               existing_nullable=True)
        batch_op.alter_column('openid',
               existing_type=mysql.VARCHAR(length=64),
               comment='微信openid',
               existing_nullable=False)

    with op.batch_alter_table('course_user', schema=None) as batch_op:
        batch_op.create_table_comment(
        '用户课程表',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_course_user_course_user_id'))
        batch_op.alter_column('course_remark',
               existing_type=mysql.TEXT(),
               comment='备注',
               existing_nullable=True)
        batch_op.alter_column('course_color',
               existing_type=mysql.VARCHAR(length=32),
               comment='显示颜色',
               existing_nullable=True,
               existing_server_default=sa.text("'#1890FF'"))
        batch_op.alter_column('classroom',
               existing_type=mysql.VARCHAR(length=128),
               comment='教室',
               existing_nullable=True)
        batch_op.alter_column('teacher_name',
               existing_type=mysql.VARCHAR(length=64),
               comment='教师姓名',
               existing_nullable=True)
        batch_op.alter_column('course_alias',
               existing_type=mysql.VARCHAR(length=128),
               comment='课程别名',
               existing_nullable=True)
        batch_op.alter_column('course_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='课程ID',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='用户ID',
               existing_nullable=False)

    with op.batch_alter_table('course_master', schema=None) as batch_op:
        batch_op.create_table_comment(
        '课程主表',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_course_master_course_id'))
        batch_op.alter_column('creator_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='创建者ID',
               existing_nullable=False)
        batch_op.alter_column('course_enabled',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否启用',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('course_keywords',
               existing_type=mysql.TEXT(),
               comment='课程关键词',
               existing_nullable=True)
        batch_op.alter_column('course_type',
               existing_type=mysql.VARCHAR(length=32),
               comment='课程类型',
               existing_nullable=False)
        batch_op.alter_column('course_name',
               existing_type=mysql.VARCHAR(length=128),
               comment='课程名称',
               existing_nullable=False)
        batch_op.alter_column('course_code',
               existing_type=mysql.VARCHAR(length=64),
               comment='课程编码',
               existing_nullable=False)

    op.create_table('schedules',
    sa.Column('id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False, comment='日程标题'),
    sa.Column('description', mysql.TEXT(), nullable=True, comment='日程描述'),
    sa.Column('start_time', mysql.DATETIME(), nullable=False, comment='开始时间'),
    sa.Column('end_time', mysql.DATETIME(), nullable=False, comment='结束时间'),
    sa.Column('location', mysql.VARCHAR(length=200), nullable=True, comment='地点'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['schedule_db.users.id'], name='schedules_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    schema='schedule_db',
    comment='日程表',
    mysql_comment='日程表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tasks',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False, comment='任务标题'),
    sa.Column('description', mysql.TEXT(), nullable=True, comment='任务描述'),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=True, comment='任务状态'),
    sa.Column('priority', mysql.VARCHAR(length=20), server_default=sa.text("'medium'"), nullable=True, comment='优先级'),
    sa.Column('due_date', mysql.DATETIME(), nullable=True, comment='截止时间'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['schedule_db.users.id'], name='tasks_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    schema='schedule_db',
    comment='任务表',
    mysql_comment='任务表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('statistics',
    sa.Column('id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('total_tasks', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='总任务数'),
    sa.Column('completed_tasks', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='已完成任务数'),
    sa.Column('total_schedules', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='总日程数'),
    sa.Column('stat_date', sa.DATE(), nullable=False, comment='统计日期'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['schedule_db.users.id'], name='statistics_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    schema='schedule_db',
    comment='统计表',
    mysql_comment='统计表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('statistics', schema='schedule_db') as batch_op:
        batch_op.create_index('idx_user_date', ['user_id', 'stat_date'], unique=True)

    op.create_table('categories',
    sa.Column('id', mysql.INTEGER(display_width=100), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('color', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='schedule_db',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('openid', mysql.VARCHAR(length=32), nullable=False, comment='微信openid'),
    sa.Column('nickname', mysql.VARCHAR(length=50), nullable=True, comment='用户昵称'),
    sa.Column('avatar_url', mysql.TEXT(), nullable=True, comment='头像URL'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    schema='schedule_db',
    comment='用户表',
    mysql_comment='用户表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema='schedule_db') as batch_op:
        batch_op.create_index('openid', ['openid'], unique=True)

    # ### end Alembic commands ###
